<?php 

class PL_Utility{


	static $uk_counties = array(
		array(
	    'Northumberland',
			'Tyne and Wear',
	    'Durham'
		),
		array(
			'Greater Manchester',
			'Merseyside',
	    'Cumbria',
	    'Lancashire',
	    'Cheshire',
	    'Isle of Man'
		),
		array(		
			'Shropshire',
			'West Midlands (county)',
	    'Worcestershire',
			'Herefordshire',
			'Staffordshire',
			'Warwickshire'
		),
		array(																
			'Nottinghamshire',
			'Lincolnshire',
			'Northamptonshire',
			'Rutland',
			'Derbyshire',
			'Leicestershire'
		),
		array(
			'North Yorkshire',
			'East riding of Yorkshire',
			'West Yorkshire',
			'South Yorkshire'
		),
		array(
			'Bedfordshire',
			'Cambridgeshire',
			'Essex',
			'Hertfordshire',
			'Norfolk',
			'Suffolk'
		),
		array(
			'Berkshire',
			'Buckinghamshire',
			'East Sussex',
			'Greater London',
			'Hampshire',
			'Isle of Wight',													
			'Kent',
			'Oxfordshire',
			'Surrey',
			'West Sussex'
		),
		array(
			'Bristol',
			'Cornwall',
			'Devon',
			'Dorset',
			'Gloucestershire',
			'Somerset',
			'Wiltshire',
			'Channel Islands'
		)
	);

	public static $countries = array(
		array(
			'EN'  =>'ENGLAND',
			'NI'  =>'NORTHERN IRELAND',
			'SC0' =>'SCOTLAND',
			'WL'  =>'WALES',
			'GB'  =>'ALL UK'
		),
		array (	  
			'AF'  =>'AFGHANISTAN',
			'AL'  =>'ALBANIA',
			'DZ'  =>'ALGERIA',
			'AS'  =>'AMERICAN SAMOA',
			'AD'  =>'ANDORRA',
			'AO'  =>'ANGOLA',
			'AI'  =>'ANGUILLA (BRITISH OVERSEAS TERRITORY)',
			'AG'  =>'ANTIGUA AND BARBUDA',
			'AR'  =>'ARGENTINA',
			'AM'  =>'ARMENIA',
			'AW'  =>'ARUBA',
			'AC'  =>'ASCENSION ISLAND (BRITISH OVERSEAS TERRITORY)',
			'AU'  =>'AUSTRALIA',
			'AT'  =>'AUSTRIA',
			'AZ'  =>'AZERBAIJAN',
			'BS'  =>'BAHAMAS',
			'BH'  =>'BAHRAIN, THE KINGDOM OF',
			'BD'  =>'BANGLADESH',
			'BB'  =>'BARBADOS',
			'BY'  =>'BELARUS',
			'BE'  =>'BELGIUM',
			'BZ'  =>'BELIZE',
			'BJ'  =>'BENIN',
			'BM'  =>'BERMUDA',
			'BT'  =>'BHUTAN',
			'BO'  =>'BOLIVIA',
			'BA'  =>'BOSNIA AND HERZEGOVINA',
			'BW'  =>'BOTSWANA',
			'BR'  =>'BRAZIL',
			'BN'  =>'BRITISH ANTARCTIC TERRITORY',
			'IO'  =>'BRITISH INDIAN OCEAN TERRITORY',
			'VG'  =>'BRITISH VIRGIN ISLANDS (BRITISH OVERSEAS TERRITORY)',
			'BN'  =>'BRUNEI',
			'BG'  =>'BULGARIA',
			'BF'  =>'BURKINA FASO',
			'BU'  =>'BURMA', 
			'BI'  =>'BURUNDI',
			'KH'  =>'CAMBODIA',
			'CM'  =>'CAMEROON',
			'CA'  =>'CANADA',
			'CV'  =>'CAPE VERDE',
			'KY'  =>'CAYMAN ISLANDS',
			'CF'  =>'CENTRAL AFRICAN REPUBLIC',
			'TD'  =>'CHAD',
			'CL'  =>'CHILE',
			'CN'  =>'CHINA',
			'CO'  =>'COLOMBIA',
			'KM'  =>'COMOROS',
			'CG'  =>'CONGO, REPUBLIC OF',
			'CD'  =>'CONGO, THE DEMOCRATIC REPUBLIC OF',
			'CR'  =>'COSTA RICA',
			'CI'  =>'C&Ocirc;TE D&acute;IVOIRE (IVORY COAST)',
			'HR'  =>'CROATIA',
			'CU'  =>'CUBA',
			'CR'  =>'CURA&Ccedil;AO', 
			'CY'  =>'CYPRUS',
			'CZ'  =>'CZECH REPUBLIC',
			'DK'  =>'DENMARK',
			'DJ'  =>'DJIBOUTI',
			'DM'  =>'DOMINICA, COMMONWEALTH OF',
			'DO'  =>'DOMINICAN REPUBLIC',
			'TP'  =>'EAST TIMOR (TIMOR-LESTE)',
			'EC'  =>'ECUADOR',
			'EG'  =>'EGYPT',
			'SV'  =>'EL SALVADOR',
			'GQ'  =>'EQUATORIAL GUINEA',
			'ER'  =>'ERITREA',
			'EE'  =>'ESTONIA',
			'ET'  =>'ETHIOPIA',
			'FK'  =>'FALKLAND ISLANDS (MALVINAS)',
			'FO'  =>'FAROE ISLANDS',
			'FJ'  =>'FIJI',
			'FI'  =>'FINLAND',
			'FR'  =>'FRANCE',
			'GF'  =>'FRENCH GUIANA',
			'PF'  =>'FRENCH POLYNESIA',
			'GA'  =>'GABON',
			'GM'  =>'GAMBIA, THE',
			'GE'  =>'GEORGIA',
			'DE'  =>'GERMANY',
			'GH'  =>'GHANA',
			'GI'  =>'GIBRALTAR',
			'GR'  =>'GREECE',
			'GL'  =>'GREENLAND',
			'GD'  =>'GRENADA',
			'GP'  =>'GUADELOUPE',
			'GU'  =>'GUAM',
			'GT'  =>'GUATEMALA',
			'GN'  =>'GUINEA',
			'GW'  =>'GUINEA-BISSAU',
			'GY'  =>'GUYANA',
			'HT'  =>'HAITI',
			'VA'  =>'HOLY SEE (VATICAN CITY STATE)',
			'HN'  =>'HONDURAS',
			'HK'  =>'HONG KONG (SAR OF CHINA)',
			'HU'  =>'HUNGARY',
			'IS'  =>'ICELAND',
			'IN'  =>'INDIA',
			'ID'  =>'INDONESIA',
			'IR'  =>'IRAN',
			'IQ'  =>'IRAQ',
			'IE'  =>'IRELAND',
			'IL'  =>'ISRAEL',
			'IT'  =>'ITALY',
			'JM'  =>'JAMAICA',
			'JP'  =>'JAPAN',
			'JO'  =>'JORDAN',
			'KZ'  =>'KAZAKHSTAN',
			'KE'  =>'KENYA',
			'KI'  =>'KIRIBATI',
			'KP'  =>'SOUTH KOREA (ROK)',
			'KR'  =>'NORTH KOREA (DPR KOREA)',
			'KS'  =>'KOSOVO',
			'KW'  =>'KUWAIT',
			'KG'  =>'KYRGYZSTAN',
			'LA'  =>'LAOS',
			'LV'  =>'LATVIA',
			'LB'  =>'LEBANON',
			'LS'  =>'LESOTHO',
			'LR'  =>'LIBERIA',
			'LY'  =>'LIBYA',
			'LI'  =>'LIECHTENSTEIN',
			'LT'  =>'LITHUANIA',
			'LU'  =>'LUXEMBOURG',
			'MO'  =>'MACAO',
			'MK'  =>'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
			'MG'  =>'MADAGASCAR',
			'MW'  =>'MALAWI',
			'MY'  =>'MALAYSIA',
			'MV'  =>'MALDIVES',
			'ML'  =>'MALI',
			'MT'  =>'MALTA',
			'MH'  =>'MARSHALL ISLANDS, REPUBLIC OF',
			'MQ'  =>'MARTINIQUE',
			'MR'  =>'MAURITANIA',
			'MU'  =>'MAURITIUS',
			'YT'  =>'MAYOTTE',
			'MX'  =>'MEXICO',
			'FM'  =>'MICRONESIA',
			'MD'  =>'MOLDOVA',
			'MC'  =>'MONACO',
			'MN'  =>'MONGOLIA',
			'ME'  =>'MONTENEGRO',
			'MS'  =>'MONTSERRAT (BRITISH OVERSEAS TERRITORY)',
			'MA'  =>'MOROCCO',
			'MZ'  =>'MOZAMBIQUE',
			'NA'  =>'NAMIBIA',
			'NR'  =>'NAURU',
			'NP'  =>'NEPAL',
			'NL'  =>'NETHERLANDS',
			'AN'  =>'NETHERLANDS ANTILLES',
			'NC'  =>'NEW CALEDONIA',
			'NZ'  =>'NEW ZEALAND',
			'NI'  =>'NICARAGUA',
			'NE'  =>'NIGER',
			'NG'  =>'NIGERIA',
			'NO'  =>'NORWAY',
			'OM'  =>'OMAN',
			'PK'  =>'PAKISTAN',
			'PW'  =>'PALAU',
			'PS'  =>'PALESTINIAN TERRITORIES',
			'PA'  =>'PANAMA',
			'PG'  =>'PAPUA NEW GUINEA',
			'PY'  =>'PARAGUAY',
			'PE'  =>'PERU',
			'PH'  =>'PHILIPPINES',
			'PN'  =>'PITCAIRN',
			'PL'  =>'POLAND',
			'PT'  =>'PORTUGAL',
			'PR'  =>'PUERTO RICO',
			'QA'  =>'QATAR',
			'RE'  =>'REUNION',
			'RO'  =>'ROMANIA',
			'RU'  =>'RUSSIAN FEDERATION',
			'RW'  =>'RWANDA',
			'SH'  =>'SAINT HELENA',
			'KN'  =>'SAINT KITTS AND NEVIS',
			'LC'  =>'SAINT LUCIA',
			'PM'  =>'SAINT PIERRE AND MIQUELON',
			'VC'  =>'SAINT VINCENT AND THE GRENADINES',
			'WS'  =>'SAMOA',
			'SM'  =>'SAN MARINO',
			'ST'  =>'SAO TOME AND PRINCIPE',
			'SA'  =>'SAUDI ARABIA',
			'SN'  =>'SENEGAL',
			'SX'  =>'SERBIA',
			'SC'  =>'SEYCHELLES',
			'SL'  =>'SIERRA LEONE',
			'SG'  =>'SINGAPORE',
			'SK'  =>'SLOVAKIA',
			'SI'  =>'SLOVENIA',
			'SB'  =>'SOLOMON ISLANDS',
			'SO'  =>'SOMALIA',
			'ZA'  =>'SOUTH AFRICA',
			'GS'  =>'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
			'SS'  =>'SOUTH SUDAN',
			'ES'  =>'SPAIN',
			'LK'  =>'SRI LANKA',
			'SAH' =>'SAINT HELENA',
			'SAK' =>'SAINT KITTS AND NEVIS',
			'SAL' =>'SAINT LUCIA',
			'SAM' =>'SAINT MAARTEN',
			'SD'  =>'SUDAN',
			'SR'  =>'SURINAME',
			'SZ'  =>'SWAZILAND',
			'SE'  =>'SWEDEN',
			'CH'  =>'SWITZERLAND',
			'SY'  =>'SYRIA',
			'TW'  =>'TAIWAN',
			'TJ'  =>'TAJIKISTAN',
			'TZ'  =>'TANZANIA',
			'TH'  =>'THAILAND',
			'TG'  =>'TOGO',
			'TO'  =>'TONGA',
			'TT'  =>'TRINIDAD AND TOBAGO',
			'TD'  =>'TRISTAN DA CUNHA',
			'TN'  =>'TUNISIA',
			'TR'  =>'TURKEY',
			'TM'  =>'TURKMENISTAN',
			'TC'  =>'TURKS AND CAICOS ISLANDS (BRITISH OVERSEAS TERRITORY)',
			'TV'  =>'TUVALU',
			'UG'  =>'UGANDA',
			'UA'  =>'UKRAINE',
			'AE'  =>'UNITED ARAB EMIRATES',
			'US'  =>'UNITED STATES',
			'UM'  =>'UNITED STATES MINOR OUTLYING ISLANDS',
			'UY'  =>'URUGUAY',
			'UZ'  =>'UZBEKISTAN',
			'VU'  =>'VANUATU',
			'VE'  =>'VENEZUELA',
			'VN'  =>'VIETNAM',
			'VI'  =>'VIRGIN ISLANDS, U.S.',
			'WF'  =>'WALLIS AND FUTUNA',
			'EH'  =>'WESTERN SAHARA',
			'YE'  =>'YEMEN',
			'ZM'  =>'ZAMBIA',
			'ZW'  =>'ZIMBABWE' 
		) );
}